---
title: "Probability Distribution Exporer"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
libs = c("ggplot2", "shinythemes")
lapply(libs, require, character.only = T)
```

#### Use the tabs below to navigate to your preferred probability distribution and update the parameters to view the resultant probability density.

```{r utils}
sliderInput01 <- function(id, label) {
  sliderInput(id, label = label, min = 0, max = 1, value = 0.5, step = 0.01)
}
```



```{r viewDistributions}
# Discrete Variables ####
# Binomial
# Number of successes in n trials
pbinomd = function(x = 1:10, # number of successes (0 above n)
                   n = 5, # the number of Bernoulli trials run
                   p = 0.5 # probability that each Bernoulli trial is a success
){
   dens = dbinom(x = x, size = n, prob = p)
   df = data.frame(Value = x, Density = dens)
   with(df, barplot(Density~Value, 
                    main = "Binomial Probability Distribution",
                    xlab = paste0("Number of successes in ", n, 
                                  " trials with a ", p*100, 
                                  "% probability of success.")))
}
# pbinomd()


# Bernoulli
# Binomial with N = 1. One run of an experiment with a binary outcome (e.g., toss a coin; can get either heads or tails)
pbernd = function(x = 0:1, # fail/success
                  p = 0.8 # probability that the Bernoulli trial is a success
){
   dens = dbinom(x = x, size = 1, prob = p)
   df = data.frame(Value = x, Density = dens)
   with(df, barplot(Density~Value, 
                    main = "Bernoulli Probability Distribution",
                    xlab = paste0("Fails (0) and successes (1) in a trial with a ", 
                                  p*100, "% probability of success")))
}
# pbernd()


# Poisson
# Probability of a fixed number of events in a given interval (often of time or space), given that events occur at a constant rate
ppoisd = function(x = 1:10, # number of events
                  lambda = 5 # the rate at which events occur
){
   dens = dpois(x = x, lambda = lambda, log = F)
   df = data.frame(Value = x, Density = dens)
   with(df, barplot(Density~Value, 
                    main = "Poisson Probability Distribution",
                    xlab = paste0("Number of events occurring at a rate of ", lambda)))
}
# ppoisd()

plpoisd = function(x = 1:10, # number of events
                  lambda = 5 # the rate at which events occur
){
   dens = dpois(x = x, lambda = lambda, log = T)
   df = data.frame(Value = x, Density = dens)
   with(df, barplot(Density~Value, main = "Poisson Log-Probability Distribution",
                    xlab = paste0("Number of events occurring at a rate of ", lambda)))
}
# plpoisd()


# Negative Binomial
# In a sequence of independent and identically distributed Bernoulli trials with success probability p, if X = number of trials until the rth success, then X ~ NBin(r, p).
pnbinomd = function(x = 1:100, # number of trials until rth success
         r = 50, # number successes required
         p = 0.5 # success probability
){
   dens = dnbinom(x = x, size = r, prob = p)
   df = data.frame(Value = x, Density = dens)
   with(df, barplot(Density~Value, 
                    main = "Negative Binomial Probability Distribution",
                    xlab = paste0("Number of trials until the ", r,
                                  "th success with a probability of ", p*100, 
                                  "% per trial")))
}
# pnbinomd()

# Geometric
# In a sequence of independent and identically distributed Bernoulli trials with success probability p, if X = number of trials until the 1st success, then X ~ Geo(p).
pgeomd = function(x = 1:10, # number of trials until first success
                  p = 0.5 # success probability
){
   dens = dgeom(x = x, prob = p, log = F)
   df = data.frame(Value = x, Density = dens)
   with(df, barplot(Density~Value, main = "Geometric Probability Distribution",
                    xlab = paste0("Number of trials until the 1st success with 
                               a probability of ", p*100, 
                                  "% per trial")))
}
# pgeomd()

plgeomd = function(x = 1:10, # number of trials until first success
                   p = 0.5 # success probability
){
   dens = dgeom(x = x, prob = p, log = T)
   df = data.frame(Value = x, Density = dens)
   with(df, barplot(Density~Value, main = "Geometric Log-Probability Distribution",
                    xlab = paste0("Number of trials until the 1st success with 
                               a probability of ", p*100, 
                                  "% per trial")))
}
# plgeomd()

# Hypergeometric
# In a population of total size N with two types of individuals, Type 1 and Type 2 (M type 1's and N - M type 2's), X = number of Type 1's in a sample of size n drawn without replacement
phyperd = function(draws = 1:10, # number of type 1's drawn in sample os size = trials
                   type1 = 5, # number of individuals of type 1
                   type2 = 5, # number of individuals of type 2
                   trials = 8 # number of trials
){
   dens = dhyper(x = draws, m = type1, n = type2, k = trials, log = F)
   df = data.frame(Value = draws, Density = dens)
   with(df, barplot(Density~Value, main = "Hypergeometric Probability Distribution",
                    xlab = paste0("Number of As in a sample drawn without replacement in ", trials, " trials from a pop with ", type1, " As and ", 
                                  type2, " Bs")))
}
# phyperd()

# Continuous Variables ####
# Uniform
# Within some bounded interval, all outcomes have an equal probability of occurrence.
punifd = function(x = seq(0, 1, by = 0.01), # outcome
                  a = 0.1, # minumum value
                  b = 0.9 # maxumum value
){
   dens = dunif(x = x, min = a, max = b)
   df = data.frame(Value = x, Density = dens)
   ggplot(df) + geom_line(aes(x = Value, y = Density)) + 
      theme_minimal() + labs(title = "Uniform Probability Distribution",
                             x = paste0("Outcomes within minimum, ", a, 
                                        ", and maximum, ", b))
}
# punifd()

# Normal
# Among other process bases, according to the Central Limit Theorem, the averages of samples of observations of random variables independently drawn from independent distributions converge in distribution to the normal
pnormd = function(x = seq(0, 100, by = 0.01), # outcome
                  mu = 25, # mean value
                  sigma = 2 # standard deviation
){
   dens = dnorm(x =x, mean = mu, sd = sigma, log = F)
   df = data.frame(Value = x, Density = dens)
   ggplot(df) + geom_line(aes(x = Value, y = Density)) + 
      theme_minimal() + labs(title = "Normal Probability Distribution",
                             x = paste0("Outcomes with a mean of ", mu, 
                                        " and a standard deviation of ", sigma))
}
# pnormd()

plnormd = function(x = seq(0, 5, by = 0.01), # outcome
                   mu = 5, # mean value
                   sigma = 2, # standard deviation
                   logpars = F # whether input is log scale or not - if false - take log
){
  mu = ifelse(logpars, mu, log(mu))
  sigma = ifelse(logpars, sigma, log(sigma))
  dens = dlnorm(x = x, meanlog = mu, sdlog = sigma)
  df = data.frame(Value = x, Density = dens)
  ggplot(df) + geom_line(aes(x = Value, y = Density)) + 
    theme_minimal() + labs(title = "Log-Normal Probability Distribution",
                           x = paste0("Outcomes with a mean of ", round(exp(mu), 2), 
                                      " and a standard deviation of ", round(exp(sigma), 2), 
                                      " (meanlog = ", round(mu, 2), 
                                      ", sdlog = ", round(sigma, 2), ")"))
}
# plnormd()

# Exponential
# Describes the time between events in a Poisson point process
pexpd = function(x = seq(0, 1, by = 0.01), # outcome
                  rate = 5 # rate at which events occur
){
   dens = dexp(x = x, rate = rate)
   df = data.frame(Value = x, Density = dens)
   ggplot(df) + geom_line(aes(x = Value, y = Density)) + 
      theme_minimal() + labs(title = "Exponential Probability Distribution",
                             x = paste0("Outcomes occurring with a rate of ", rate))
}
# pexpd()

# Gamma
# A stochastic process with independent, non-negative increments having a gamma distribution with an identical scale parameter and a time-dependent shape parameter.
pgammad = function(x = seq(0, 1, by = 0.01), # outcome
                   alpha = 5, # shape parameter
                   beta = 2 # rate paramter 
){
   mu = round(alpha / beta, digits = 1)
   sigma = round(alpha / beta^2, digits = 1)
   dens = dgamma(x = x, shape = alpha, rate = beta)
   df = data.frame(Value = x, Density = dens)
   ggplot(df) + geom_line(aes(x = Value, y = Density)) + 
      theme_minimal() + labs(title = "Gamma Probability Distribution",
                             x = paste0("Outcomes occurring with a mean of ", mu,
                                        " and a standard deviation of ", sigma, 
                                        " (alpha = ", alpha, " and beta = ", beta, 
                                        ")"))
}
# pgammad()

# Beta
# Continuous distribution bounded to lie between 0 and 1. Commonly used as a distribution describing p, the per-trial success probability for Bernoulli trials.
pbetad = function(x = seq(0, 1, by = 0.01), # outcome
                   alpha = 5, # shape parameter 1
                   beta = 2 # shape paramter 2
){
   mu = alpha / (alpha + beta)
   mu = round(mu, digits = 1)
   sigma = (alpha * beta) / ((alpha + beta)^2 * (alpha + beta + 1))
   sigma = round(sigma, digits = 1)
   dens = dbeta(x = x, shape1 = alpha, shape2 = beta)
   df = data.frame(Value = x, Density = dens)
   ggplot(df) + geom_line(aes(x = Value, y = Density)) + 
      theme_minimal() + labs(title = "Beta Probability Distribution",
                             x = paste0("Outcomes occurring with a mean of ", mu,
                                        " and a standard deviation of ", sigma, 
                                        " (alpha = ", alpha, " and beta = ", beta, 
                                        ")"))
} 
# pbetad()

# Von Mises
# he maximum entropy distribution for circular data when the real and imaginary parts of the first circular moment are specified

pvonmisesd = function(x = seq(-pi, pi, by = 0.01), # outcome
                  mu = 1, # mean direction
                  kappa = 0.1 # concentrtion around mean
){
   dens = circular::dvonmises(x = x, mu = mu, kappa = kappa)
   df = data.frame(Value = x, Density = dens)
   ggplot(df) + geom_line(aes(x = Value, y = Density)) + coord_polar() +
      theme_minimal() + labs(title = "Von Mises Probability Distribution",
                             x = paste0("Angles occuring with a mean of ", mu,
                                        " radians and a concentration of ", kappa))
}
# pvonmisesd()
```



```{r, echo = FALSE}
# Define UI for application that graphs probability distributions
ui <- fluidPage(
  theme = shinytheme("sandstone"),

  tabsetPanel(
    # Discrete Panel ####
    tabPanel("Discrete", navlistPanel(
      #####
      tabPanel(title = "Binomial",
               h3("Parameters"),
               fluidRow(
                 column(6,
                        h4("Number of Trials:"),
                        numericInput("binom_n", label = NULL,
                                     min = 1, step = 1, value = 1))
                 ,
                 column(6,
                        h4("Probability of Success:"),
                        sliderInput01(id = "binom_p", label = NULL))
                 ) # End row
               ,
               h3("Inputs"),
               fluidRow(
                 column(6,
                        h4("Minimum Trials:"),
                        numericInput("binom_min", label = NULL, value = 1,
                                     min = 1, step = 1)),
                 column(6,
                        h4("Maximum Trials:"),
                        numericInput("binom_max", label = NULL, value = 10,
                                     step = 1, min = 3))
                 ) # End row
               ,
               plotOutput("plot_binom")), # End of inner tabPanel
      #####
      tabPanel(title = "Bernoulli",
               h3("Parameters")
               ,
               fluidRow(
                 column(12,
                        h4("Probability of Success:"),
                        sliderInput("bern_p", label = NULL,
                                    min = 0, max = 1, step = 0.01, value = 0.5))
                 ) # End row
               ,
               plotOutput("plot_bern")), # End of inner tabPanel
      #####
      tabPanel(title = "Poisson",
               h3("Parameters")
               ,
               fluidRow(
                 column(12,
                        h4("Rate At Which Events Occur:"),
                        numericInput("pois_lambda", label = NULL,
                                     min = 0, step = 1, value = 1))
                 ) # End row
               ,
               h3("Inputs"),
               fluidRow(
                 column(6,
                        h4("Minimum Count:"),
                        numericInput("pois_min", label = NULL, value = 0,
                                     min = 0, step = 1))
                 ,
                 column(6,
                        h4("Maximum Count:"),
                        numericInput("pois_max", label = NULL, value = 10,
                                     step = 1, min = 3))
                 ) # End row
               ,
               plotOutput("plot_pois")), # End of inner tabPanel
      #####
      tabPanel(title = "Negative Binomial",
               h3("Parameters")
               ,
               fluidRow(
                 column(6,
                        h4("Number of Successes Required:"),
                        numericInput("nbinom_r", label = NULL,
                                     min = 1, step = 1, value = 1))
                 ,
                 column(6,
                        h4("Probability of Success:"),
                        sliderInput01(id = "nbinom_p", label = NULL))
               ) # End row
               ,
               h3("Inputs"),
               fluidRow(
                 column(6,
                        h4("Minimum Trials Until rth Success:"),
                        numericInput("nbinom_min", label = NULL, value = 1,
                                     min = 1, step = 1))
                 ,
                 column(6,
                        h4("Maximum Trials Until rth Success:"),
                        numericInput("nbinom_max", label = NULL, value = 10,
                                     step = 1, min = 3))
                 ) # End row
               ,
               plotOutput("plot_nbinom")), # End of inner tabPanel
      #####
      tabPanel(title = "Geometric",
               h3("Parameters")
               ,
               fluidRow(
                 column(6,
                        h4("Probability of Success:"),
                        sliderInput("geom_p", label = NULL,
                                    min = 0, max = 1, step = 0.01, value = 0.5))
                 ) # End row
               ,
               h3("Inputs"),
               fluidRow(
                 column(6,
                        h4("Minimum Trials Until 1st Success:"),
                        numericInput("geom_min", label = NULL, value = 1,
                                     min = 1, step = 1))
                 ,
                 column(6,
                        h4("Maximum Trials Until 1st Success:"),
                        numericInput("geom_max", label = NULL, value = 10,
                                     step = 1, min = 3))
                 ) # End row
               ,
               plotOutput("plot_geom")), # End of inner tabPanel
      #####
      tabPanel(title = "Hyper Geometric",
               h3("Parameters")
               ,
               fluidRow(
                 column(6,
                        h4("Population of Type 1's:"),
                        numericInput("hyper_type1", label = NULL, value = 5,
                                     min = 1, step = 1))
                 ,
                 column(6,
                        h4("Population of Type 2's"),
                        numericInput("hyper_type2", label = NULL, value = 5,
                                     step = 1, min = 1))
                 ) # End row
               ,
               h3("Inputs"),
               fluidRow(
                 column(6,
                        h4("Number of Type 1's Drawn:"),
                        numericInput("hyper_draws", label = NULL,
                                     min = 1, step = 1, value = 1))
                 ,
                 column(6,
                        h4("Number of Trials"),
                        numericInput("hyper_trials", label = NULL,
                                     min = 1, step = 1, value = 1))
                 ) # End row
               ,
               plotOutput("plot_hyper"))# End of inner tabPanel
      #####
      ) # End of navlistPanel
    ) # End of discrete tabPanel
    ,
    # Continuous Panel ####
    tabPanel("Continuous", navlistPanel(
      #####
      tabPanel(title = "Uniform",
               h3("Parameters")
               ,
               fluidRow(
                 column(6,
                        h4("Minimum Value (a):"),
                        numericInput("unif_a", label = NULL, value = 6,
                                     step = 0.5)),
                 column(6,
                        h4("Maximum Value (b):"),
                        numericInput("unif_b", label = NULL, value = 9,
                                     step = 0.5))
                 ) # End row
               ,
               h3("Inputs"),
               fluidRow(
                 column(6,
                        h4("Minimum Outcome:"),
                        numericInput("unif_min", label = NULL, step = 0.5,
                                     value = 0))
                 ,
                 column(6,
                        h4("Maximum Outcome:"),
                        numericInput("unif_max", label = NULL, step = 0.5,
                                     value = 15))
                 ) # End row
               ,
               plotOutput("plot_unif")), # End of inner tabPanel
      #####
      tabPanel(title = "Normal",
               h3("Parameters")
               ,
               fluidRow(
                 column(6,
                        h4("Mean Outcome:"),
                        numericInput("norm_mu", label = NULL, value = 0,
                                     step = 0.1)),
                 column(6,
                        h4("Standard Deviation:"),
                        numericInput("norm_sigma", label = NULL, value = 1,
                                     step = 0.1))
                 ) # End row
               ,
               h3("Inputs"),
               fluidRow(
                 column(6,
                        h4("Minimum Outcome:"),
                        numericInput("norm_min", label = NULL, step = 0.5,
                                     value = -5))
                 ,
                 column(6,
                        h4("Maximum Outcome:"),
                        numericInput("norm_max", label = NULL, step = 0.5,
                                     value = 5))
                 ) # End row
               ,
               plotOutput("plot_norm")), # End of inner tabPanel
      #####
            tabPanel(title = "Log-Normal",
               h3("Parameters")
               ,
               fluidRow(
                 column(4,
                        h4("Mean Outcome:"),
                        numericInput("lnorm_mu", label = NULL, value = 2,
                                     step = 0.1)),
                 column(4,
                        h4("Standard Deviation:"),
                        numericInput("lnorm_sigma", label = NULL, value = 2,
                                     step = 0.1)),
                 column(4,
                        h4("Are Parameters on the Log Scale?"),
                        checkboxInput("logpars", label = NULL, value = FALSE, width = NULL))
                 ) # End row
               ,
               h3("Inputs"),
               fluidRow(
                 column(6,
                        h4("Minimum Outcome:"),
                        numericInput("lnorm_min", label = NULL, step = 0.5,
                                     value = 0))
                 ,
                 column(6,
                        h4("Maximum Outcome:"),
                        numericInput("lnorm_max", label = NULL, step = 0.5,
                                     value = 15))
                 ) # End row
               ,
               plotOutput("plot_lnorm")), # End of inner tabPanel
      #####
      tabPanel(title = "Exponential",
               h3("Parameters")
               ,
               fluidRow(
                 column(6,
                        h4("Rate At Which Events Occur:"),
                        numericInput("exp_rate", label = NULL, value = 2.5,
                                     step = 0.1))
                 ) # End row
               ,
               h3("Inputs"),
               fluidRow(
                 column(6,
                        h4("Minimum Outcome:"),
                        numericInput("exp_min", label = NULL, step = 0.5,
                                     value = 1))
                 ,
                 column(6,
                        h4("Maximum Outcome:"),
                        numericInput("exp_max", label = NULL, step = 0.5,
                                     value = 15))
                 ) # End row
               ,
               plotOutput("plot_exp")), # End of inner tabPanel
      #####
      tabPanel(title = "Gamma",
               h3("Parameters"),
               fluidRow(
                 column(6,
                        h4("Alpha:"),
                        numericInput("gamma_alpha", label = NULL, value = 5,
                                     step = 0.1)),
                 column(6,
                        h4("Beta:"),
                        numericInput("gamma_beta", label = NULL, value = 2.5,
                                     step = 0.1))
                 ) # End row
               ,
               h3("Inputs"),
               fluidRow(
                 column(6,
                        h4("Minimum Outcome:"),
                        numericInput("gamma_min", label = NULL, step = 0.5,
                                     value = 1))
                 ,
                 column(6,
                        h4("Maximum Outcome:"),
                        numericInput("gamma_max", label = NULL, step = 0.5,
                                     value = 15))
                 ) # End row
               ,
               plotOutput("plot_gamma")), # End of inner tabPanel
      #####
      tabPanel(title = "Beta",
               h3("Parameters")
               ,
               fluidRow(
                 column(6,
                        h4("Alpha:"),
                        numericInput("beta_alpha", label = NULL, value = 1,
                                     step = 0.1)),
                 column(6,
                        h4("Beta:"),
                        numericInput("beta_beta", label = NULL, value = 1,
                                     step = 0.1))
                 ) # End row
               ,
               plotOutput("plot_beta")), # End of inner tabPanel
      #####
      tabPanel(title = "Von Mises",
               h3("Parameters")
               ,
               fluidRow(
                 column(6,
                        h4("Mean Outcome:"),
                        numericInput("vonmises_mu", label = NULL, value = 0,
                                     step = 0.1)),
                 column(6,
                        h4("Concentration:"),
                        numericInput("vonmises_kappa", label = NULL, value = 1,
                                     step = 0.1))
                 ) # End row
               ,
               plotOutput("plot_vonmises")) # End of inner tabPanel
      #####
      ) # end of navlistPanel
    ) # End of outer tabPanel
  ) # End of tabsetPanel
) # End of UI

# Define server logic required to draw a histogram
server <- function(input, output) {
  # Discrete Plots
  output$plot_binom <- renderPlot({
    x = seq(input$binom_min, input$binom_max, by = 1)
    pbinomd(x = x, n = input$binom_n, p = input$binom_p)
    })
  output$plot_bern <- renderPlot({
    pbernd(p = input$bern_p)
    })
  output$plot_pois <- renderPlot({
    x = seq(input$pois_min, input$pois_max, by = 1)
    ppoisd(x = x, lambda = input$pois_lambda)
    })
  output$plot_nbinom <- renderPlot({
    x = seq(input$nbinom_min, input$nbinom_max, by = 1)
    pnbinomd(x = x, r = input$nbinom_r, p = input$nbinom_p)
    })
  output$plot_geom <- renderPlot({
    x = seq(input$geom_min, input$geom_max, by = 1)
    pgeomd(x = x, p = input$geom_p)
    })
  output$plot_hyper <- renderPlot({
    phyperd(draws = input$hyper_draws, type1 = input$hyper_type1,
            type2 = input$hyper_type2, trials = input$hyper_trials)
    })
  # Continuous Plots
  output$plot_unif <- renderPlot({
    x = seq(input$unif_min, input$unif_max, by = 0.01)
    punifd(x = x, a = input$unif_a, b = input$unif_b)
    })
  output$plot_norm <- renderPlot({
    x = seq(input$norm_min, input$norm_max, by = 0.01)
    pnormd(x = x, mu = input$norm_mu, sigma = input$norm_sigma)
    })
    output$plot_lnorm <- renderPlot({
    x = seq(input$lnorm_min, input$lnorm_max, by = 0.01)
    plnormd(x = x, mu = input$lnorm_mu, sigma = input$lnorm_sigma, logpars = input$logpars)
    })
  output$plot_exp <- renderPlot({
    x = seq(input$exp_min, input$exp_max, by = 0.01)
    pexpd(x = x, rate = input$exp_rate)
    })
  output$plot_gamma <- renderPlot({
    x = seq(input$gamma_min, input$gamma_max, by = 0.01)
    pgammad(x = x, alpha = input$gamma_alpha, beta = input$gamma_beta)
    })
  output$plot_beta <- renderPlot({
    pbetad(alpha = input$beta_alpha, beta = input$beta_beta)
    })
  output$plot_vonmises <- renderPlot({
    pvonmisesd(mu = input$vonmises_mu, kappa = input$vonmises_kappa)
    })
} # end of server function

# Run the application
shinyApp(ui = ui, server = server, 
         options = list(height = 800, width = "100%"))
# shiny::reactlogShow()
```


**Created by L. R. McDonald on 2022-02-23.**